version: '3.8'

services:
  discord-voice-mcp:
    build:
      context: .
      dockerfile: Dockerfile.dev
    
    container_name: discord-voice-mcp-dev
    
    environment:
      # Discord Configuration (Required)
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}
      DISCORD_GUILD_ID: ${DISCORD_GUILD_ID:-}
      
      # Development Settings
      NODE_ENV: development
      LOG_LEVEL: debug
      DEBUG: "*"
      
      # Transcription Configuration
      TRANSCRIPTION_PROVIDER: ${TRANSCRIPTION_PROVIDER:-whisper}
      WHISPER_MODEL_NAME: ${WHISPER_MODEL_NAME:-base.en}
      VOSK_MODEL_SIZE: ${VOSK_MODEL_SIZE:-small}
      AUTO_DOWNLOAD_MODELS: ${AUTO_DOWNLOAD_MODELS:-true}
    
    volumes:
      # Mount source code for hot reload
      - ./src:/app/src
      - ./scripts:/app/scripts
      # Persistent data
      - ./models:/app/models
      - ./sessions:/app/sessions
      - ./credentials:/app/credentials:ro
    
    ports:
      # Node.js debugger
      - "9229:9229"
    
    # More resources for development
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4G