version: '3.8'

services:
  discord-voice-mcp:
    build: .
    image: discord-voice-mcp:latest
    container_name: discord-voice-mcp
    restart: unless-stopped
    
    environment:
      # Discord Configuration (Required)
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}
      DISCORD_GUILD_ID: ${DISCORD_GUILD_ID:-}
      
      # Transcription Configuration
      TRANSCRIPTION_PROVIDER: ${TRANSCRIPTION_PROVIDER:-whisper}
      WHISPER_MODEL_NAME: ${WHISPER_MODEL_NAME:-base.en}
      VOSK_MODEL_SIZE: ${VOSK_MODEL_SIZE:-small}
      
      # Optional Settings
      LOG_LEVEL: ${LOG_LEVEL:-info}
      AUTO_DOWNLOAD_MODELS: ${AUTO_DOWNLOAD_MODELS:-true}
    
    volumes:
      # Persist models to avoid re-downloading
      - models:/app/models
      # Store session transcripts
      - sessions:/app/sessions
      # Google Cloud credentials (if using Google provider)
      - ./credentials:/app/credentials:ro
    
    # Resource limits
    deploy:
      resources:
        limits:
          cpus: '${CPU_LIMIT:-2}'
          memory: ${MEMORY_LIMIT:-2G}

volumes:
  models:
    name: discord-voice-mcp_models
  sessions:
    name: discord-voice-mcp_sessions